server:
  port: 8761

eureka:
  client:
#    不要使用eureka服务进行注册（应该客户端注册）
    register-with-eureka: false
#    不要在本地缓存注册表信息（应该客户端缓存）
    fetchRegistry: false
  server:
#    在服务器接收请求之前等待的时间
    wait-time-in-ms-when-sync-empty: 5
  service-url:
    default-zone: http://localhost:8761
