server:
  port: 8081
spring:
  application:
    name: organizationservice
  profiles:
    active: dev
  cloud:
    config:
      enabled: true
    stream:
      bindings:
        # 通道名称，映射到代码中是source.output()的主题
        output:
          # 写入消息的消息队列的名称
          destination: orgChangeTopic
          content-type: application/json
      # 告诉spring使用kakfa作为消息总线（可以使用RabbitMQ）
      kafka:
        binder:
          # 下面两个属性告诉stream，kafka和Zookeeper的网络位置
          zk-nodes: localhost:2181
          brokers: localhost:9092
eureka:
  instance:
    # 注册服务的IP,而不是服务器名称
    prefer-ip-address: true
  client:
    # 向uereka注册服务
    register-with-eureka: true
    # 拉取注册表的本地副本
    fetch-registry: true
    service-url:
      # eureka服务的位置
      defaultZone: http://localhost:8761/eureka/
#security:
#  oauth2:
#    resource:
#      user-info-uri: http://localhost:8901/auth/user
