server:
  port: 8888
spring:
  cloud:
    config:
      server:
#---------------------------------------------
#        禁止config服务器端解密（防止调用方直接拿到明文）
        encrypt:
          enabled: false
        #        将配置信息从git仓库获取
        git:
          uri: https://github.com/LiouChong/cloud-in-action-config/
          search-paths: licensingservice,organizationservice,zuulservice,specialroutesservice,orgservice-new
          username:
          password:
#--------------------------------------------
#        将配置信息从本地库读取。
#        native:
#          search-locations: file:D:\IDEA\IDEA_Space\cloud-in-action\cloud-in-action\confsvr\src\main\resources\config\licensingservice

encrypt:
  key: Antiy