server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:G:\IDEA_SPACE\cloud-in-action\confsvr\src\main\resources\config\licensingservice
